import jsPDF from "jspdf";
import type { HandoffData } from "./handoff";
import type { Project } from "./projects";

// ─── Colours ──────────────────────────────────────────────────────────────────
const C = {
  navyR: 10,  navyG: 15,  navyB: 26,   // #0a0f1a
  orngR: 249, orngG: 115, orngB: 22,   // #F97316
  ornDR: 234, ornDG: 88,  ornDB: 12,   // #EA580C (dark orange)
  g900R: 28,  g900G: 25,  g900B: 23,   // #1C1917
  g700R: 68,  g700G: 64,  g700B: 60,   // #44403C
  g500R: 87,  g500G: 83,  g500B: 78,   // #57534E
  g400R: 120, g400G: 113, g400B: 108,  // #78716C
  g300R: 168, g300G: 162, g300B: 158,  // #A8A29E
  g200R: 231, g200G: 229, g200B: 228,  // #E7E5E4
  g100R: 245, g100G: 245, g100B: 244,  // #F5F5F4
  whtR:  255, whtG:  255, whtB:  255,
  // Status
  greenR: 21,  greenG: 128, greenB: 61,   // #15803D
  amberR: 161, amberG: 98,  amberB: 7,    // #A16207
  redR:   190, redG:  18,   redB:  60,    // #BE123C
};

function fmtDate(d: string): string {
  if (!d) return "—";
  try {
    return new Date(d + "T00:00:00").toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  } catch {
    return d;
  }
}

// ─── Layout constants ─────────────────────────────────────────────────────────
const PW    = 215.9; // letter width mm
const PH    = 279.4; // letter height mm
const ML    = 16;    // left margin
const MR    = 16;    // right margin
const CW    = PW - ML - MR; // content width
const HEADER_H = 26; // dark bar height
const SUB_H    = 10; // orange sub-bar height
const FOOTER_H = 12;
const TOP_Y    = HEADER_H + SUB_H + 8; // first content y

// ─── Main export ──────────────────────────────────────────────────────────────

export function generateKickoffPDF(
  project: Project,
  data: HandoffData,
  pmName = "Jake Morrison",
  logoDataUrl?: string,
) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });

  // Running y cursor
  let y = TOP_Y;

  // ── Draw page chrome on the current page ──────────────────────────────────
  function drawChrome() {
    // Dark navy header bar
    doc.setFillColor(C.navyR, C.navyG, C.navyB);
    doc.rect(0, 0, PW, HEADER_H, "F");

    // Orange left accent stripe
    doc.setFillColor(C.orngR, C.orngG, C.orngB);
    doc.rect(0, 0, 4.5, HEADER_H, "F");

    // Logo or fallback text
    if (logoDataUrl) {
      // Image is 1024×1024 with ~44% content area — render at 28×28mm so the
      // content fills the dark header bar nicely with slight bleed top/bottom.
      doc.addImage(logoDataUrl, "PNG", 7, -1, 28, 28);
    } else {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(15);
      doc.setTextColor(C.whtR, C.whtG, C.whtB);
      doc.text("Foreplannr", 10, 16.5);
    }

    // "Kickoff Report" — orange, smaller, offset right of logo
    const labelX = logoDataUrl ? 37 : 10;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(C.orngR, C.orngG, C.orngB);
    doc.text("Kickoff Report", labelX, 22.5);

    // Project name — right aligned, light gray
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(C.g300R, C.g300G, C.g300B);
    const pnW = doc.getTextWidth(project.name);
    doc.text(project.name, PW - MR - pnW, 16.5);
    if (project.client) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(C.g400R, C.g400G, C.g400B);
      const clientW = doc.getTextWidth(project.client);
      doc.text(project.client, PW - MR - clientW, 22.5);
    }

    // Orange sub-bar
    doc.setFillColor(C.orngR, C.orngG, C.orngB);
    doc.rect(0, HEADER_H, PW, SUB_H, "F");

    const dateStr = new Date().toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    });
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    doc.setTextColor(C.whtR, C.whtG, C.whtB);
    doc.text(
      `Prepared: ${dateStr}   ·   Project Manager: ${pmName}`,
      ML,
      HEADER_H + 6.8,
    );

    // Footer bar
    doc.setFillColor(C.navyR, C.navyG, C.navyB);
    doc.rect(0, PH - FOOTER_H, PW, FOOTER_H, "F");
  }

  // ── Footer text for a specific page ──────────────────────────────────────
  function drawFooter(pageNum: number, totalPages: number) {
    doc.setPage(pageNum);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);

    // Left: project name
    doc.setTextColor(C.g400R, C.g400G, C.g400B);
    doc.text(project.name, ML, PH - 4.5);

    // Right: "Generated by Foreplannr"
    doc.setTextColor(C.orngR, C.orngG, C.orngB);
    const genText = "Generated by Foreplannr";
    const genW = doc.getTextWidth(genText);
    doc.text(genText, PW - MR - genW, PH - 4.5);

    // Centre: page number (only if multi-page)
    if (totalPages > 1) {
      doc.setTextColor(C.g400R, C.g400G, C.g400B);
      const pg = `Page ${pageNum} of ${totalPages}`;
      const pgW = doc.getTextWidth(pg);
      doc.text(pg, (PW - pgW) / 2, PH - 4.5);
    }
  }

  // ── Page-break guard ──────────────────────────────────────────────────────
  function need(h: number) {
    const usableBottom = PH - FOOTER_H - 4;
    if (y + h > usableBottom) {
      doc.addPage();
      drawChrome();
      y = TOP_Y;
    }
  }

  // ── Section header ────────────────────────────────────────────────────────
  function sectionHeader(title: string) {
    need(18);
    // Orange left rule
    doc.setFillColor(C.orngR, C.orngG, C.orngB);
    doc.rect(ML, y, 3, 9, "F");

    // Title text
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(C.ornDR, C.ornDG, C.ornDB);
    doc.text(title.toUpperCase(), ML + 6, y + 6.5);
    y += 12;

    // Thin divider
    doc.setDrawColor(C.g200R, C.g200G, C.g200B);
    doc.setLineWidth(0.25);
    doc.line(ML, y, PW - MR, y);
    y += 5;
  }

  // ── Label helper ─────────────────────────────────────────────────────────
  function smallLabel(txt: string) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    doc.setTextColor(C.g300R, C.g300G, C.g300B);
    doc.text(txt.toUpperCase(), ML, y);
    y += 4.5;
  }

  // ── Body text helper (auto word-wrap, multi-page safe) ────────────────────
  function bodyText(txt: string, indent = 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(C.g700R, C.g700G, C.g700B);
    const lines = doc.splitTextToSize(txt, CW - indent);
    // write line by line so page breaks are safe
    for (const line of lines) {
      need(6);
      doc.text(line, ML + indent, y);
      y += 5.2;
    }
    y += 2;
  }

  // ── Labelled field ────────────────────────────────────────────────────────
  function field(label: string, value: string) {
    if (!value) return;
    need(16);
    smallLabel(label);
    bodyText(value);
    y += 1;
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Draw first page chrome
  drawChrome();

  // ══ SECTION 1 — Scope Summary ════════════════════════════════════════════
  sectionHeader("Scope Summary");
  if (data.scopeSummary) {
    need(10);
    bodyText(data.scopeSummary);
  } else {
    need(8);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(C.g300R, C.g300G, C.g300B);
    doc.text("No scope summary provided.", ML, y);
    y += 6;
  }

  if (data.keyExclusions) {
    need(14);
    smallLabel("Key Exclusions / Clarifications");
    bodyText(data.keyExclusions);
  }

  if (data.contractDocName) {
    need(14);
    smallLabel("Contract Document");
    bodyText(data.contractDocName);
  }

  y += 4;

  // ══ SECTION 2 — Drawing Status ═══════════════════════════════════════════
  sectionHeader("Drawing Status");
  field("Drawing Set", data.drawingSetName);
  field("Revision / Date Confirmed", data.drawingRevision);
  if (data.drawingIssues) {
    need(14);
    smallLabel("Known Issues / RFIs to Flag");
    bodyText(data.drawingIssues);
  }
  if (!data.drawingSetName && !data.drawingRevision && !data.drawingIssues) {
    need(8);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(C.g300R, C.g300G, C.g300B);
    doc.text("No drawing information provided.", ML, y);
    y += 6;
  }

  y += 4;

  // ══ SECTION 3 — Project Milestones ═══════════════════════════════════════
  sectionHeader("Project Milestones");

  // Key date trio
  if (data.projectStart || data.substantialCompletion || data.finalCompletion) {
    need(22);
    const colW = CW / 3;
    const dateCols = [
      { label: "Project Start",           val: fmtDate(data.projectStart) },
      { label: "Substantial Completion",  val: fmtDate(data.substantialCompletion) },
      { label: "Final Completion",        val: fmtDate(data.finalCompletion) },
    ];
    dateCols.forEach((col, i) => {
      const x = ML + i * colW;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7.5);
      doc.setTextColor(C.g300R, C.g300G, C.g300B);
      doc.text(col.label.toUpperCase(), x, y);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10.5);
      doc.setTextColor(C.g900R, C.g900G, C.g900B);
      doc.text(col.val || "—", x, y + 7);
    });
    y += 17;
  }

  // Milestones table
  if (data.milestones.length > 0) {
    need(16);
    // Table header row
    doc.setFillColor(C.g100R, C.g100G, C.g100B);
    doc.rect(ML, y, CW, 8, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    doc.setTextColor(C.g400R, C.g400G, C.g400B);
    doc.text("MILESTONE", ML + 3, y + 5.5);
    const dtLabel = "TARGET DATE";
    const dtLW = doc.getTextWidth(dtLabel);
    doc.text(dtLabel, PW - MR - 3 - dtLW, y + 5.5);
    y += 8;

    data.milestones.forEach((m, i) => {
      need(9);
      if (i % 2 === 0) {
        doc.setFillColor(250, 250, 249);
        doc.rect(ML, y, CW, 8, "F");
      }
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(C.g900R, C.g900G, C.g900B);
      doc.text(m.name || "—", ML + 3, y + 5.5);
      const dt = fmtDate(m.date);
      const dtW = doc.getTextWidth(dt);
      doc.text(dt, PW - MR - 3 - dtW, y + 5.5);
      doc.setDrawColor(C.g200R, C.g200G, C.g200B);
      doc.setLineWidth(0.2);
      doc.line(ML, y + 8, PW - MR, y + 8);
      y += 8;
    });
    y += 4;
  } else if (!data.projectStart && !data.substantialCompletion && !data.finalCompletion) {
    need(8);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(C.g300R, C.g300G, C.g300B);
    doc.text("No milestone data provided.", ML, y);
    y += 6;
  }

  y += 4;

  // ══ SECTION 4 — Permit Status ═════════════════════════════════════════════
  sectionHeader("Permit Status");

  if (data.permits.length > 0) {
    need(16);
    // Column x positions
    const colX = {
      type:   ML + 3,
      number: ML + 52,
      issue:  ML + 96,
      exp:    ML + 130,
      status: ML + 163,
    };

    // Table header
    doc.setFillColor(C.g100R, C.g100G, C.g100B);
    doc.rect(ML, y, CW, 8, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    doc.setTextColor(C.g400R, C.g400G, C.g400B);
    doc.text("PERMIT TYPE", colX.type,   y + 5.5);
    doc.text("NUMBER",      colX.number, y + 5.5);
    doc.text("ISSUED",      colX.issue,  y + 5.5);
    doc.text("EXPIRES",     colX.exp,    y + 5.5);
    doc.text("STATUS",      colX.status, y + 5.5);
    y += 8;

    data.permits.forEach((p, i) => {
      need(9);
      if (i % 2 === 0) {
        doc.setFillColor(250, 250, 249);
        doc.rect(ML, y, CW, 8, "F");
      }
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(C.g900R, C.g900G, C.g900B);
      doc.text(p.type   || "—", colX.type,   y + 5.5);
      doc.text(p.number || "—", colX.number, y + 5.5);
      doc.text(fmtDate(p.issueDate), colX.issue,  y + 5.5);
      doc.text(fmtDate(p.expDate),   colX.exp,    y + 5.5);

      // Status with colour coding
      doc.setFont("helvetica", "bold");
      if (p.status === "Issued") {
        doc.setTextColor(C.greenR, C.greenG, C.greenB);
      } else if (p.status === "Pending") {
        doc.setTextColor(C.amberR, C.amberG, C.amberB);
      } else {
        doc.setTextColor(C.redR, C.redG, C.redB);
      }
      doc.text(p.status, colX.status, y + 5.5);

      doc.setDrawColor(C.g200R, C.g200G, C.g200B);
      doc.setLineWidth(0.2);
      doc.line(ML, y + 8, PW - MR, y + 8);
      y += 8;
    });
    y += 4;
  } else {
    need(8);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(C.g300R, C.g300G, C.g300B);
    doc.text("No permits on record.", ML, y);
    y += 6;
  }

  if (data.permitNotes) {
    need(14);
    smallLabel("Permit Notes");
    bodyText(data.permitNotes);
  }

  y += 4;

  // ══ SECTION 5 — Site Logistics ════════════════════════════════════════════
  sectionHeader("Site Logistics");
  field("Site Access",        data.siteAccess);
  field("Parking",            data.parking);
  field("Staging Area",       data.stagingArea);
  if (data.safetyRequirements) {
    need(14);
    smallLabel("Safety Requirements");
    bodyText(data.safetyRequirements);
  }
  if (data.keyContacts) {
    need(14);
    smallLabel("Key On-Site Contacts");
    bodyText(data.keyContacts);
  }
  if (!data.siteAccess && !data.parking && !data.stagingArea && !data.safetyRequirements && !data.keyContacts) {
    need(8);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(C.g300R, C.g300G, C.g300B);
    doc.text("No site logistics information provided.", ML, y);
    y += 6;
  }

  y += 4;

  // ══ SECTION 6 — Next Steps ════════════════════════════════════════════════
  sectionHeader("Next Steps");

  const nextSteps = [
    "Start logging RFIs",
    "Set up submittal tracker",
    "Schedule subcontractor kickoff meeting",
    "Review permit expiration dates",
  ];

  nextSteps.forEach((step) => {
    need(10);
    // Checkbox outline
    doc.setDrawColor(C.orngR, C.orngG, C.orngB);
    doc.setFillColor(C.whtR, C.whtG, C.whtB);
    doc.setLineWidth(0.6);
    doc.rect(ML, y - 5.5, 5, 5, "FD");

    // Step text
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(C.g700R, C.g700G, C.g700B);
    doc.text(step, ML + 8, y - 1.2);
    y += 8.5;
  });

  // ─────────────────────────────────────────────────────────────────────────
  // Stamp footers on every page
  const totalPages = doc.getNumberOfPages();
  for (let pg = 1; pg <= totalPages; pg++) {
    drawFooter(pg, totalPages);
  }

  // Save
  const safeName = project.name.replace(/[^a-z0-9]/gi, "_").toLowerCase();
  doc.save(`${safeName}_kickoff_report.pdf`);
}
