import { jsPDF } from "jspdf";
import type { TurnoverMeeting, TurnoverContact, TurnoverStep } from "./turnover";
import type { Project } from "./projects";

// ─── Colors ──────────────────────────────────────────────────────────────────
const C = {
  orange:      [249, 115, 22]  as [number, number, number],
  orangeLight: [255, 247, 237] as [number, number, number],
  dark:        [28,  25,  23]  as [number, number, number],
  gray:        [120, 113, 108] as [number, number, number],
  mid:         [168, 162, 158] as [number, number, number],
  lgray:       [231, 229, 228] as [number, number, number],
  white:       [255, 255, 255] as [number, number, number],
  vlight:      [250, 250, 249] as [number, number, number],
  greenLight:  [240, 253, 244] as [number, number, number],
  green:       [34,  197, 94]  as [number, number, number],
  greenDark:   [21,  128, 61]  as [number, number, number],
  greenMid:    [134, 239, 172] as [number, number, number],
};

// ─── Page metrics ─────────────────────────────────────────────────────────────
const PW = 215.9;  // letter width mm
const PH = 279.4;  // letter height mm
const ML = 18;     // left margin
const MR = 18;     // right margin
const CW = PW - ML - MR;  // content width ~180mm
const FOOTER_H = 18;
const FOOTER_Y = PH - FOOTER_H;

// ─── Helpers ─────────────────────────────────────────────────────────────────

function tc(doc: jsPDF, c: [number, number, number]) { doc.setTextColor(c[0], c[1], c[2]); }
function fc(doc: jsPDF, c: [number, number, number]) { doc.setFillColor(c[0], c[1], c[2]); }
function dc(doc: jsPDF, c: [number, number, number]) { doc.setDrawColor(c[0], c[1], c[2]); }

function hRule(doc: jsPDF, y: number, color = C.lgray, lw = 0.25) {
  dc(doc, color);
  doc.setLineWidth(lw);
  doc.line(ML, y, PW - MR, y);
}

function trunc(str: string, max: number): string {
  if (!str) return "—";
  return str.length > max ? str.slice(0, max - 1) + "…" : str;
}

async function loadLogoDataUrl(): Promise<string | null> {
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => {
      try {
        const canvas = document.createElement("canvas");
        const scale = 4;
        canvas.width  = (img.naturalWidth  || 160) * scale;
        canvas.height = (img.naturalHeight || 50)  * scale;
        const ctx = canvas.getContext("2d");
        if (!ctx) { resolve(null); return; }
        ctx.scale(scale, scale);
        ctx.drawImage(img, 0, 0);
        resolve(canvas.toDataURL("image/png"));
      } catch { resolve(null); }
    };
    img.onerror = () => resolve(null);
    img.src = "/exportsvg_copy_foreplannr.svg";
  });
}

function drawFooter(doc: jsPDF, generatedAt: string) {
  dc(doc, C.lgray);
  doc.setLineWidth(0.25);
  doc.line(ML, FOOTER_Y, PW - MR, FOOTER_Y);
  tc(doc, C.mid);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.text("Generated by Foreplannr — foreplannr.com", ML, FOOTER_Y + 5);
  doc.text("Confidential — for internal use only", ML, FOOTER_Y + 10);
  doc.text(generatedAt, PW - MR, FOOTER_Y + 5, { align: "right" });
}

function checkBreak(doc: jsPDF, y: number, needed: number, generatedAt: string): number {
  if (y + needed > FOOTER_Y - 8) {
    drawFooter(doc, generatedAt);
    doc.addPage();
    return 18;
  }
  return y;
}

function sectionHeader(doc: jsPDF, title: string, y: number): number {
  fc(doc, C.orange);
  doc.rect(ML, y, 3, 6.5, "F");
  tc(doc, C.dark);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9.5);
  doc.text(title, ML + 6, y + 5);
  y += 10;
  hRule(doc, y, C.lgray);
  return y + 5;
}

// ─── Main export ─────────────────────────────────────────────────────────────

export async function generateTurnoverPDF(
  project: Project,
  meeting: TurnoverMeeting,
  contacts: TurnoverContact[],
  steps: TurnoverStep[],
  pmName: string
): Promise<void> {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });

  const generatedAt = new Date().toLocaleString("en-US", {
    month: "short", day: "numeric", year: "numeric",
    hour: "numeric", minute: "2-digit",
  });
  const dateOnly = new Date().toLocaleDateString("en-US", {
    month: "long", day: "numeric", year: "numeric",
  });

  // ── HEADER BAR ──────────────────────────────────────────────────────────────
  fc(doc, C.orange);
  doc.rect(0, 0, PW, 20, "F");

  const logoData = await loadLogoDataUrl();
  if (logoData) {
    // Render logo on orange bar — white logo so we try directly; if it has
    // transparent bg it'll composite over the orange naturally
    doc.addImage(logoData, "PNG", ML, 4, 32, 12);
  } else {
    tc(doc, C.white);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text("FOREPLANNR", ML, 14);
  }

  tc(doc, C.white);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("PROJECT TURNOVER SHEET", PW - MR, 13, { align: "right" });

  // ── PROJECT META ─────────────────────────────────────────────────────────────
  let y = 30;

  tc(doc, C.dark);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text(project.name, ML, y);
  y += 8;

  const metaCols = [
    { label: "Customer",         value: project.client || "—" },
    { label: "Project Manager",  value: pmName || "—" },
    { label: "Date Generated",   value: dateOnly },
  ];
  const metaColW = CW / 3;
  doc.setFontSize(8);
  metaCols.forEach((item, i) => {
    const x = ML + i * metaColW;
    tc(doc, C.mid);
    doc.setFont("helvetica", "normal");
    doc.text(item.label.toUpperCase(), x, y);
    tc(doc, C.dark);
    doc.setFont("helvetica", "bold");
    doc.text(trunc(item.value, 30), x, y + 5);
  });
  y += 12;

  hRule(doc, y, C.orange, 0.6);
  y += 8;

  // ─────────────────────────────────────────────────────────────────────────────
  // SECTION 1 — JOB CONTACTS
  // ─────────────────────────────────────────────────────────────────────────────
  y = checkBreak(doc, y, 35, generatedAt);
  y = sectionHeader(doc, "1. JOB CONTACTS", y);

  const filled = contacts.filter((c) => c.name.trim() || c.role.trim());

  if (filled.length === 0) {
    tc(doc, C.mid);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8.5);
    doc.text("No contacts entered.", ML, y + 3);
    y += 10;
  } else {
    // Column x positions
    const cX = [ML, ML + 38, ML + 88, ML + 128];
    const headers = ["Role", "Name", "Phone", "Email"];
    const rowH = 7;

    // Header row
    fc(doc, C.orangeLight);
    doc.rect(ML, y - 1, CW, rowH + 1, "F");
    tc(doc, C.orange);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    headers.forEach((h, i) => doc.text(h, cX[i] + 2, y + 5));
    y += rowH + 2;
    hRule(doc, y, C.lgray);
    y += 1;

    filled.forEach((c, idx) => {
      y = checkBreak(doc, y, rowH + 2, generatedAt);
      if (idx % 2 === 0) {
        fc(doc, C.vlight);
        doc.rect(ML, y - 1, CW, rowH + 1, "F");
      }
      tc(doc, C.dark);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      const vals = [trunc(c.role, 22), trunc(c.name, 26), c.phone || "—", trunc(c.email, 28)];
      vals.forEach((v, i) => doc.text(v, cX[i] + 2, y + 5));
      y += rowH + 1;
    });
    y += 5;
  }

  // ─────────────────────────────────────────────────────────────────────────────
  // SECTION 2 — JOB SITE REQUIREMENTS  (two-column grid)
  // ─────────────────────────────────────────────────────────────────────────────
  y = checkBreak(doc, y, 30, generatedAt);
  y = sectionHeader(doc, "2. JOB SITE REQUIREMENTS", y);

  const siteFields = [
    { label: "Site Access Instructions",  value: meeting.siteAccess },
    { label: "Delivery Requirements",     value: meeting.deliveryRequirements },
    { label: "Special Handling",          value: meeting.specialHandling },
    { label: "Safety Requirements",       value: meeting.safetyRequirements },
    { label: "Parking and Staging Area",  value: meeting.parkingStaging },
  ];

  const halfW = (CW - 8) / 2;
  const col2X = ML + halfW + 8;
  const labelH = 5;
  const lineH  = 4.2;

  for (let i = 0; i < siteFields.length; i += 2) {
    const left  = siteFields[i];
    const right = siteFields[i + 1];

    const leftLines  = doc.splitTextToSize(left.value || "—", halfW - 2);
    const rightLines = right ? doc.splitTextToSize(right.value || "—", halfW - 2) : [];

    const leftH  = labelH + leftLines.length  * lineH + 3;
    const rightH = right  ? labelH + rightLines.length * lineH + 3 : 0;
    const blockH = Math.max(leftH, rightH);

    y = checkBreak(doc, y, blockH + 4, generatedAt);

    // Left
    tc(doc, C.gray);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    doc.text(left.label.toUpperCase(), ML, y + 4);
    tc(doc, C.dark);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.text(leftLines, ML, y + 4 + labelH);

    // Right
    if (right) {
      tc(doc, C.gray);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7.5);
      doc.text(right.label.toUpperCase(), col2X, y + 4);
      tc(doc, C.dark);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.text(rightLines, col2X, y + 4 + labelH);
    }

    y += blockH + 2;
    if (i + 2 < siteFields.length) {
      hRule(doc, y, C.lgray, 0.15);
      y += 4;
    }
  }
  y += 6;

  // ─────────────────────────────────────────────────────────────────────────────
  // SECTION 3 — PROJECT DETAILS
  // ─────────────────────────────────────────────────────────────────────────────
  y = checkBreak(doc, y, 30, generatedAt);
  y = sectionHeader(doc, "3. PROJECT DETAILS", y);

  const detailFields = [
    { label: "Confirmed Scope of Work",      value: meeting.scopeOfWork },
    { label: "Key Exclusions",               value: meeting.keyExclusions },
    { label: "Special Order Items to Flag",  value: meeting.specialOrderItems },
    { label: "Lead Time Concerns",           value: meeting.leadTimeConcerns },
  ];

  detailFields.forEach((field, idx) => {
    const lines  = doc.splitTextToSize(field.value || "—", CW - 2);
    const blockH = labelH + lines.length * lineH + 3;

    y = checkBreak(doc, y, blockH + 4, generatedAt);

    tc(doc, C.gray);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    doc.text(field.label.toUpperCase(), ML, y + 4);

    tc(doc, C.dark);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.text(lines, ML, y + 4 + labelH);

    y += blockH + 2;
    if (idx < detailFields.length - 1) {
      hRule(doc, y, C.lgray, 0.15);
      y += 4;
    }
  });
  y += 6;

  // ─────────────────────────────────────────────────────────────────────────────
  // SECTION 4 — PM CHECKLIST
  // ─────────────────────────────────────────────────────────────────────────────
  y = checkBreak(doc, y, 30, generatedAt);
  y = sectionHeader(doc, "4. PM CHECKLIST", y);

  const stepRowH = 7.5;
  const cbSize   = 3.5;

  steps.forEach((step, i) => {
    y = checkBreak(doc, y, stepRowH + 2, generatedAt);

    const isDone = step.status === "done";

    // Row background
    if (isDone) {
      fc(doc, C.greenLight);
      doc.rect(ML, y - 0.5, CW, stepRowH + 1, "F");
    } else if (i % 2 === 0) {
      fc(doc, C.vlight);
      doc.rect(ML, y - 0.5, CW, stepRowH + 1, "F");
    }

    // Checkbox
    const cbX = ML + 2;
    const cbY = y + 1.5;

    if (isDone) {
      fc(doc, C.green);
      doc.rect(cbX, cbY, cbSize, cbSize, "F");
      // Checkmark drawn as two lines
      dc(doc, C.white);
      doc.setLineWidth(0.7);
      doc.line(cbX + 0.6, cbY + 1.8, cbX + 1.4, cbY + 2.7);
      doc.line(cbX + 1.4, cbY + 2.7, cbX + 2.9, cbY + 0.7);
    } else {
      dc(doc, C.lgray);
      doc.setLineWidth(0.4);
      doc.rect(cbX, cbY, cbSize, cbSize, "S");
    }

    // Step index
    tc(doc, isDone ? C.greenMid : C.mid);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    doc.text(String(i + 1).padStart(2, "0"), cbX + 6, y + 5);

    // Title
    tc(doc, isDone ? C.greenDark : C.dark);
    doc.setFont("helvetica", isDone ? "normal" : "normal");
    doc.setFontSize(8.5);
    doc.text(trunc(step.title || "Untitled step", 70), cbX + 14, y + 5);

    // Due date
    if (step.dueDate) {
      const due = new Date(step.dueDate + "T00:00:00").toLocaleDateString("en-US", {
        month: "short", day: "numeric",
      });
      tc(doc, isDone ? C.greenDark : C.mid);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.text(`Due ${due}`, PW - MR, y + 5, { align: "right" });
    }

    y += stepRowH;
    hRule(doc, y, C.lgray, 0.1);
    y += 1;
  });

  // ── Footer on final page ────────────────────────────────────────────────────
  drawFooter(doc, generatedAt);

  // ── Save ───────────────────────────────────────────────────────────────────
  const safeName = project.name
    .replace(/[^a-zA-Z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-");
  doc.save(`${safeName}-Turnover-Sheet.pdf`);
}
